library(teal.modules.general)

# data = teal_data(
#   iris = iris,
#   code = "
#     iris <- iris
#   "
# )
# 
# app <- init(
#   data = data,
#   modules = list(
#     tm_g_distribution(
#       dist_var = data_extract_spec(
#         dataname = "iris",
#         select = select_spec(variable_choices("iris"), "Petal.Length")
#       ),
#       ggplot2_args = teal.widgets::ggplot2_args(
#         labs = list(subtitle = "Plot generated by Distribution Module")
#       )
#     )
#   )
# )
# 
# if (interactive()) {
#   shinyApp(app$ui, app$server)
# }

library(teal.modules.general)
library(teal.widgets)
data <- teal_data()
data <- within(data, {
  ADSL <- rADSL
})
datanames(data) <- c("ADSL")
join_keys(data) <- default_cdisc_join_keys[datanames(data)]

vars1 <- choices_selected(
  variable_choices(data[["ADSL"]], c("ARM", "COUNTRY", "SEX")),
  selected = NULL
)

app <- init(
  data = data,
  modules = modules(
    tm_g_distribution(
      dist_var = data_extract_spec(
        dataname = "ADSL",
        select = select_spec(
          choices = variable_choices(data[["ADSL"]], c("AGE", "BMRKR1")),
          selected = "BMRKR1",
          multiple = FALSE,
          fixed = FALSE
        )
      ),
      strata_var = data_extract_spec(
        dataname = "ADSL",
        filter = filter_spec(
          vars = vars1,
          multiple = TRUE
        )
      ),
      group_var = data_extract_spec(
        dataname = "ADSL",
        filter = filter_spec(
          vars = vars1,
          multiple = TRUE
        )
      ),
      ggplot2_args = ggplot2_args(
        labs = list(subtitle = "Plot generated by Distribution Module")
      )
    )
  )
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}
