library(teal.modules.general)


data = teal_data(
  iris = iris,
  code = "
    iris <- iris
  "
)

app <- init(
  data = data,
  modules = list(
    tm_g_distribution(
      dist_var = data_extract_spec(
        dataname = "iris",
        select = select_spec(variable_choices("iris"), "Petal.Length")
      ),
      ggplot2_args = teal.widgets::ggplot2_args(
        labs = list(subtitle = "Plot generated by Distribution Module")
      )
    )
  )
)

if (interactive()) {
  shinyApp(app$ui, app$server)
}
